name: CI + CodeQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 18 * * 4'

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: javascript-typescript
            build-mode: manual
          - language: python
            build-mode: manual

    steps:
      # 1. Clonar repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configuración para JavaScript/React
      - name: Set up Node.js
        if: matrix.language == 'javascript-typescript'
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 3. Configuración para Python
      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 4. Inicializar CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      # 5. Build manual según lenguaje
      - name: Manual build for JavaScript/React
        if: matrix.language == 'javascript-typescript'
        run: |
          npm install
          npm run build
          npm run lint
          npm test

      - name: Manual build for Python
        if: matrix.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8
          flake8 .
          pytest

      # 6. Análisis de seguridad
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
